package service

import (
	"log"
	"net/http"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
)

var Timezones = make(map[string]string)

func InitDictionary() {
	Timezones["AD"] = "Europe/Andorra"
	Timezones["AE"] = "Asia/Dubai"
	Timezones["AF"] = "Asia/Kabul"
	Timezones["AG"] = "America/Antigua"
	Timezones["AI"] = "America/Anguilla"
	Timezones["AL"] = "Europe/Tirane"
	Timezones["AM"] = "Asia/Yerevan"
	Timezones["AO"] = "Africa/Luanda"
	Timezones["AQ"] = "Antarctica/Casey"
	Timezones["AR"] = "America/Argentina/Buenos_Aires"
	Timezones["AS"] = "Pacific/Pago_Pago"
	Timezones["AT"] = "Europe/Vienna"
	Timezones["AU"] = "Antarctica/Macquarie"
	Timezones["AW"] = "America/Aruba"
	Timezones["AX"] = "Europe/Mariehamn"
	Timezones["AZ"] = "Asia/Baku"
	Timezones["BA"] = "Europe/Sarajevo"
	Timezones["BB"] = "America/Barbados"
	Timezones["BD"] = "Asia/Dacca"
	Timezones["BD"] = "Asia/Dhaka"
	Timezones["BE"] = "Europe/Brussels"
	Timezones["BF"] = "Africa/Ouagadougou"
	Timezones["BG"] = "Europe/Sofia"
	Timezones["BH"] = "Asia/Bahrain"
	Timezones["BI"] = "Africa/Bujumbura"
	Timezones["BJ"] = "Africa/Porto-Novo"
	Timezones["BL"] = "America/St_Barthelemy"
	Timezones["BM"] = "Atlantic/Bermuda"
	Timezones["BN"] = "Asia/Brunei"
	Timezones["BO"] = "America/La_Paz"
	Timezones["BR"] = "Brazil/Acre"
	Timezones["BS"] = "America/Nassau"
	Timezones["BT"] = "Asia/Thimbu"
	Timezones["BW"] = "Africa/Gaborone"
	Timezones["BY"] = "Europe/Minsk"
	Timezones["BZ"] = "America/Belize"
	Timezones["CA"] = "Canada/Atlantic"
	Timezones["CD"] = "Africa/Kinshasa"
	Timezones["CF"] = "Africa/Bangui"
	Timezones["CG"] = "Africa/Brazzaville"
	Timezones["CH"] = "Europe/Zurich"
	Timezones["CI"] = "Africa/Abidjan"
	Timezones["CK"] = "Pacific/Rarotonga"
	Timezones["CL"] = "Chile/Continental"
	Timezones["CM"] = "Africa/Douala"
	Timezones["CN"] = "Asia/Shanghai"
	Timezones["CO"] = "America/Bogota"
	Timezones["CR"] = "America/Costa_Rica"
	Timezones["CU"] = "Cuba"
	Timezones["CV"] = "Atlantic/Cape_Verde"
	Timezones["CW"] = "America/Curacao"
	Timezones["CX"] = "Indian/Christmas"
	Timezones["CY"] = "Asia/Famagusta"
	Timezones["CY"] = "Europe/Nicosia"
	Timezones["CZ"] = "Europe/Prague"
	Timezones["DE"] = "Europe/Berlin"
	Timezones["DJ"] = "Africa/Djibouti"
	Timezones["DK"] = "Europe/Copenhagen"
	Timezones["DM"] = "America/Dominica"
	Timezones["DO"] = "America/Santo_Domingo"
	Timezones["DZ"] = "Africa/Algiers"
	Timezones["EC"] = "America/Guayaquil"
	Timezones["EC"] = "Pacific/Galapagos"
	Timezones["EE"] = "Europe/Tallinn"
	Timezones["EG"] = "Egypt"
	Timezones["EH"] = "Africa/El_Aaiun"
	Timezones["ER"] = "Africa/Asmara"
	Timezones["ES"] = "Europe/Madrid"
	Timezones["ET"] = "Africa/Addis_Ababa"
	Timezones["FI"] = "Europe/Helsinki"
	Timezones["FJ"] = "Pacific/Fiji"
	Timezones["FK"] = "Atlantic/Stanley"
	Timezones["FM"] = "Pacific/Chuuk"
	Timezones["FO"] = "Atlantic/Faeroe"
	Timezones["FR"] = "Europe/Paris"
	Timezones["GA"] = "Africa/Libreville"
	Timezones["GB"] = "Europe/London"
	Timezones["GD"] = "America/Grenada"
	Timezones["GE"] = "Asia/Tbilisi"
	Timezones["GF"] = "America/Cayenne"
	Timezones["GG"] = "Europe/Guernsey"
	Timezones["GH"] = "Africa/Accra"
	Timezones["GI"] = "Europe/Gibraltar"
	Timezones["GM"] = "Africa/Banjul"
	Timezones["GN"] = "Africa/Conakry"
	Timezones["GP"] = "America/Guadeloupe"
	Timezones["GQ"] = "Africa/Malabo"
	Timezones["GR"] = "Europe/Athens"
	Timezones["GS"] = "Atlantic/South_Georgia"
	Timezones["GT"] = "America/Guatemala"
	Timezones["GU"] = "Pacific/Guam"
	Timezones["GW"] = "Africa/Bissau"
	Timezones["GY"] = "America/Guyana"
	Timezones["HK"] = "Asia/Hong_Kong"
	Timezones["HN"] = "America/Tegucigalpa"
	Timezones["HR"] = "Europe/Zagreb"
	Timezones["HT"] = "America/Port-au-Prince"
	Timezones["HU"] = "Europe/Budapest"
	Timezones["ID"] = "Asia/Jakarta"
	Timezones["IE"] = "Europe/Dublin"
	Timezones["IL"] = "Asia/Jerusalem"
	Timezones["IM"] = "Europe/Isle_of_Man"
	Timezones["IN"] = "Asia/Kolkata"
	Timezones["IO"] = "Indian/Chagos"
	Timezones["IR"] = "Asia/Tehran"
	Timezones["IS"] = "Atlantic/Reykjavik"
	Timezones["IT"] = "Europe/Rome"
	Timezones["JE"] = "Europe/Jersey"
	Timezones["JM"] = "America/Jamaica"
	Timezones["JO"] = "Asia/Amman"
	Timezones["JP"] = "Asia/Tokyo"
	Timezones["KE"] = "Africa/Nairobi"
	Timezones["KG"] = "Asia/Bishkek"
	Timezones["KH"] = "Asia/Phnom_Penh"
	Timezones["KI"] = "Pacific/Enderbury"
	Timezones["KM"] = "Indian/Comoro"
	Timezones["KN"] = "America/St_Kitts"
	Timezones["KP"] = "Asia/Pyongyang"
	Timezones["KR"] = "Asia/Seoul"
	Timezones["KW"] = "Asia/Kuwait"
	Timezones["KY"] = "America/Cayman"
	Timezones["KZ"] = "Asia/Almaty"
	Timezones["LA"] = "Asia/Vientiane"
	Timezones["LB"] = "Asia/Beirut"
	Timezones["LC"] = "America/St_Lucia"
	Timezones["LI"] = "Europe/Vaduz"
	Timezones["LK"] = "Asia/Colombo"
	Timezones["LR"] = "Africa/Monrovia"
	Timezones["LS"] = "Africa/Maseru"
	Timezones["LT"] = "Europe/Vilnius"
	Timezones["LU"] = "Europe/Luxembourg"
	Timezones["LV"] = "Europe/Riga"
	Timezones["LY"] = "Africa/Tripoli"
	Timezones["MA"] = "Africa/Casablanca"
	Timezones["MC"] = "Europe/Monaco"
	Timezones["MD"] = "Europe/Chisinau"
	Timezones["ME"] = "Europe/Podgorica"
	Timezones["MF"] = "America/Marigot"
	Timezones["MG"] = "Indian/Antananarivo"
	Timezones["MH"] = "Kwajalein"
	Timezones["MK"] = "Europe/Skopje"
	Timezones["ML"] = "Africa/Bamako"
	Timezones["MM"] = "Asia/Rangoon"
	Timezones["MN"] = "Asia/Choibalsan"
	Timezones["MO"] = "Asia/Macau"
	Timezones["MP"] = "Pacific/Saipan"
	Timezones["MQ"] = "America/Martinique"
	Timezones["MR"] = "Africa/Nouakchott"
	Timezones["MS"] = "America/Montserrat"
	Timezones["MT"] = "Europe/Malta"
	Timezones["MU"] = "Indian/Mauritius"
	Timezones["MV"] = "Indian/Maldives"
	Timezones["MW"] = "Africa/Blantyre"
	Timezones["MX"] = "Mexico/BajaSur"
	Timezones["MY"] = "Asia/Kuala_Lumpur"
	Timezones["MZ"] = "Africa/Maputo"
	Timezones["NA"] = "Africa/Windhoek"
	Timezones["NC"] = "Pacific/Noumea"
	Timezones["NE"] = "Africa/Niamey"
	Timezones["NF"] = "Pacific/Norfolk"
	Timezones["NG"] = "Africa/Lagos"
	Timezones["NI"] = "America/Managua"
	Timezones["NL"] = "Europe/Amsterdam"
	Timezones["NO"] = "Europe/Oslo"
	Timezones["NP"] = "Asia/Kathmandu"
	Timezones["NR"] = "Pacific/Nauru"
	Timezones["NU"] = "Pacific/Niue"
	Timezones["NZ"] = "Pacific/Auckland"
	Timezones["OM"] = "Asia/Muscat"
	Timezones["PA"] = "America/Panama"
	Timezones["PE"] = "America/Lima"
	Timezones["PF"] = "Pacific/Gambier"
	Timezones["PG"] = "Pacific/Bougainville"
	Timezones["PH"] = "Asia/Manila"
	Timezones["PK"] = "Asia/Karachi"
	Timezones["PL"] = "Europe/Warsaw"
	Timezones["PM"] = "America/Miquelon"
	Timezones["PN"] = "Pacific/Pitcairn"
	Timezones["PR"] = "America/Puerto_Rico"
	Timezones["PS"] = "Asia/Gaza"
	Timezones["PT"] = "Europe/Lisbon"
	Timezones["PW"] = "Pacific/Palau"
	Timezones["PY"] = "America/Asuncion"
	Timezones["QA"] = "Asia/Qatar"
	Timezones["RE"] = "Indian/Reunion"
	Timezones["RO"] = "Europe/Bucharest"
	Timezones["RS"] = "Europe/Belgrade"
	Timezones["RU"] = "Asia/Anadyr"
	Timezones["RW"] = "Africa/Kigali"
	Timezones["SA"] = "Asia/Riyadh"
	Timezones["SB"] = "Pacific/Guadalcanal"
	Timezones["SC"] = "Indian/Mahe"
	Timezones["SD"] = "Africa/Khartoum"
	Timezones["SE"] = "Europe/Stockholm"
	Timezones["SG"] = "Asia/Singapore"
	Timezones["SH"] = "Atlantic/St_Helena"
	Timezones["SI"] = "Europe/Ljubljana"
	Timezones["SJ"] = "Arctic/Longyearbyen"
	Timezones["SK"] = "Europe/Bratislava"
	Timezones["SL"] = "Africa/Freetown"
	Timezones["SM"] = "Europe/San_Marino"
	Timezones["SN"] = "Africa/Dakar"
	Timezones["SO"] = "Africa/Mogadishu"
	Timezones["SR"] = "America/Paramaribo"
	Timezones["SS"] = "Africa/Juba"
	Timezones["ST"] = "Africa/Sao_Tome"
	Timezones["SV"] = "America/El_Salvador"
	Timezones["SX"] = "America/Lower_Princes"
	Timezones["SY"] = "Asia/Damascus"
	Timezones["SZ"] = "Africa/Mbabane"
	Timezones["TC"] = "America/Grand_Turk"
	Timezones["TD"] = "Africa/Ndjamena"
	Timezones["TF"] = "Indian/Kerguelen"
	Timezones["TG"] = "Africa/Lome"
	Timezones["TH"] = "Asia/Bangkok"
	Timezones["TJ"] = "Asia/Dushanbe"
	Timezones["TK"] = "Pacific/Fakaofo"
	Timezones["TL"] = "Asia/Dili"
	Timezones["TM"] = "Asia/Ashgabat"
	Timezones["TN"] = "Africa/Tunis"
	Timezones["TO"] = "Pacific/Tongatapu"
	Timezones["TR"] = "Asia/Istanbul"
	Timezones["TT"] = "America/Port_of_Spain"
	Timezones["TV"] = "Pacific/Funafuti"
	Timezones["TW"] = "Asia/Taipei"
	Timezones["TZ"] = "Africa/Dar_es_Salaam"
	Timezones["UA"] = "Europe/Kiev"
	Timezones["UG"] = "Africa/Kampala"
	Timezones["UM"] = "Pacific/Johnston"
	Timezones["US"] = "America/Adak"
	Timezones["UY"] = "America/Montevideo"
	Timezones["UZ"] = "Asia/Samarkand"
	Timezones["VA"] = "Europe/Vatican"
	Timezones["VC"] = "America/St_Vincent"
	Timezones["VE"] = "America/Caracas"
	Timezones["VG"] = "America/Tortola"
	Timezones["VI"] = "America/St_Thomas"
	Timezones["VN"] = "Asia/Ho_Chi_Minh"
	Timezones["VU"] = "Pacific/Efate"
	Timezones["WF"] = "Pacific/Wallis"
	Timezones["WS"] = "Pacific/Apia"
	Timezones["YE"] = "Asia/Aden"
	Timezones["YT"] = "Indian/Mayotte"
	Timezones["ZA"] = "Africa/Johannesburg"
	Timezones["ZM"] = "Africa/Lusaka"
	Timezones["ZW"] = "Africa/Harare"
}

func GetTimeEpoch(c *gin.Context) {
	var million int64 = 1000000

	epoch := time.Now().UnixNano()
	millis := epoch / million

	c.JSON(http.StatusOK, millis)
}

func GetDateTime(c *gin.Context) {
	t := time.Now().Format("Mon Jan 2 03:04:05PM -0700 MST 2006")
	c.JSON(http.StatusOK, t)
}

func GetTimeTZ(c *gin.Context) {
	tz := c.Param("timezone")
	tz = strings.ToUpper(tz)

	loc, present := Timezones[tz]
	if !present {
		log.Println("Error: Invalid Location....Defaulting to UTC")
		loc = "UTC"
	}

	location, locationError := time.LoadLocation(loc)
	if locationError != nil {
		c.JSON(http.StatusInternalServerError, locationError.Error())
		c.Abort()
	}

	now := time.Now().In(location)
	formattedTime := now.Format("Mon Jan 2 03:04:05PM -0700 MST 2006")
	c.JSON(http.StatusOK, formattedTime)
}
